module.exports = {
  COMPANY_GET_DATA: { success: true, statusCode: 200, data: [] },
  COMPANY_CANNOT_GET_DATA: { success: false, statusCode: 400, msg: "Cannot Get Companies" },
  COMPANY_NOT_FOUND: { success: false, statusCode: 404, msg: "Company Not Found" },
  COMPANY_CREATED: { success: true, statusCode: 201, msg: "Company Created Successfully!" },
  COMPANY_CANNOT_CREATE: { success: false, statusCode: 400, msg: "Cannot Create Company" },
  COMPANY_EXIST: { success: false, statusCode: 422, msg: "Company Exist" },
  COMPANY_DELETED: { success: true, statusCode: 200, msg: "Company Deleted Successfully!" },
  COMPANY_CANNOT_DELETE: { success: false, statusCode: 422, msg: "Company Cannot Be Deleted" },
  COMPANY_OWNED: { success: true, statusCode: 200, msg: "Company Owned Successfully!" },
  COMPANY_ALREADY_OWNED: { success: false, statusCode: 422, msg: "This Company Already Owned" },
  COMPANY_ALREADY_OWNED_BY_THIS: { success: false, statusCode: 422, msg: "Already Owned By This Company!" },
  COMPANY_SELF_OWN: { success: false, statusCode: 422, msg: "Company Cannot Be Owned By Itself!" },
  COMPANY_CANNOT_BE_OWNED: { success: false, statusCode: 400, msg: "Company Cannot Be Owned" },
  STATION_GET_DATA: { success: true, statusCode: 200, data: [] },
  STATION_GET_DATA_FAILURE: { success: false, statusCode: 400, msg: "Cannot Get Stations" },
  STATION_NOT_FOUND: { success: false, statusCode: 404, msg: "Station Not Found" },
  STATION_CREATED: { success: true, statusCode: 201, msg: "Station Created Successfully!" },
  STATION_CANNOT_CREATE: { success: false, statusCode: 400, msg: "Cannot Create Station" },
  STATION_DELETED: { success: true, statusCode: 200, msg: "Stations Deleted Successfully!" },
  STATION_CANNOT_DELETE: { success: false, statusCode: 422, msg: "Cannot Delete Stations" },
  STATION_UPDATED: { success: true, statusCode: 200, msg: "Station Updated!", data: {} },
  STATION_CANNOT_UPDATE: { success: false, statusCode: 400, msg: "Cannot Update Station" },
  STATION_IN_RADIUS_GET_DATA: { success: true, statusCode: 200, data: [] },
  STATION_IN_RADIUS_GET_DATA_FAILURE: { success: false, statusCode: 400, msg: "Cannot get stations in radius!" },
  INVALID_CRED: { success: false, statusCode: 400, msg: "Invalid Credentials" },
  SERVER_ERROR: { success: false, statusCode: 500, msg: "Something Went Wrong!" }
};
